# This file configures mora_the_explorer's *default* internal settings and should not be
# changed by anyone other than the NMR department

# If you are looking for your user configuration, it is stored in the user's own
# config.toml, at:
# Windows:  %USERPROFILE%\AppData\Roaming\mora_the_explorer
# macOS:    ~/Library/Application Support/mora_the_explorer
# Linux:    $XDG_CONFIG_HOME/mora_the_explorer or ~/.config/mora_the_explorer

# The user version of config.toml is primarily used to store the set of search options
# saved by the user, however if that file contains key-value pairs for anything else
# e.g. paths.Linux, those take precedence over those specified here

[default_options]
initials = "mjm"
group = "gil"
dest_path = "copy full path here"
inc_init = false
inc_solv = false
inc_path = false  # Only for nmr - set to "after" to append path, "before" to prepend
nmrcheck_style = false
spec = "400er"
repeat_switch = false
repeat_delay = 5


[paths]
update = "mnova/mora_the_explorer"
Windows = "//mora/nmr"
Darwin = "/Volumes/nmr"         # Darwin = macOS
Linux = "will be overwritten"   # Specify in user config, not here!


[groups]
# Available groups in the style `initialism = full_name`
# The initialism is the standard one used for each group's experiments and data
# institute-wide and is used in the search for Bruker spectra (as it must be included in
# the measurement title)
# The full name is the name used for folders of the group e.g. at //mora/nmr/500-600er
fer = "fernandez"
gar = "garcia"
gil = "gilmour"
glo = "glorius"
hei = "hein"
nae = "naesborg"
rav = "ravoo"
stu = "studer"


[groups.other]
ac = "ac"
biochemie = "biochemie"
extern = "extern"
ipc = "ipc"
kb = "kb"
meet = "meet"
nmr = "nmr"
nuk = "nuk"
pharmazie = "pharmazie"


[spectrometers]
# Provide the following information for each spectrometer category:
#   spec_dir: the name of the folder for the spectrometer in \\mora\nmr
#   date: the way dates are formatted, defining <date> - for the format codes see
#       https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
#   check_paths: the paths that should be searched for new spectra
#   archives: if spectra from previous years can't be found under check_paths, give the
#             names of archive folders for previous years, including the date format
#   include: other spectrometer categories which should be searched at the same time
#   manufacturer: the manufacturer of the spectrometer(s)
#   display_name: the text shown next to the button in the user interface
#                 (note that some characters need escaping, e.g. write && for &)
#   date_entry: whether the user selects the full date "dd MMM yyyy" or just year "yyyy"
#   allow_solvent: whether to enable the folder naming option to include the solvent
#   single_check_only: whether users may use multiday and repeat checks for this spec
#   restrict_to: the list of groups that should be able to see the spectrometer - if
#                this key is not used, the spectrometer will be visible to all
#
# Possible variable fields are:
# - <spec_dir>      (the value of `spec_dir`)
# - <date>          (the value of `date`)
# - <group>         (the chosen group's initialism)
# - <group name>    (the chosen group's name)
# - any strftime formatting string, with % characters, enclosed in <>

[spectrometers.dpx]
spec_dir = "dpx300"
date = "%b%d-%Y"
check_paths = [
    "<spec_dir>/<%y>-dpx300_<%Y>/<date>",
]
manufacturer = "bruker"
display_name = "old dpx spectrometer (300 MHz)"
date_entry = "dd MMM yyyy"
allow_solvent = true
single_check_only = false
restrict_to = [
    "nmr",
]


[spectrometers.300er]
spec_dir = "300er"
date = "%b%d-%Y"
check_paths = [
    "<spec_dir>/<date>",
]
archives = [
    "<spec_dir>/<%y>-av300_<%Y>/<date>",
    "<spec_dir>/<%y>-dpx300_<%Y>/<date>",
]
manufacturer = "bruker"
display_name = "Studer group NMR only (300 MHz)"
date_entry = "dd MMM yyyy"
allow_solvent = true
single_check_only = false
restrict_to = [
    "nmr",
    "stu",
    "nae",
]


[spectrometers.400er]
spec_dir = "400er"
date = "%b%d-%Y"
check_paths = [
    "<spec_dir>/neo400a_<date>",
    "<spec_dir>/neo400b_<date>",
    "<spec_dir>/neo400c_<date>",
]
archives = [
    "<spec_dir>/<%y>-av400_<%Y>/<date>",
    "<spec_dir>/<%y>-neo400a_<%Y>/<date>",
    "<spec_dir>/<%y>-neo400b_<%Y>/<date>",
    "<spec_dir>/<%y>-neo400c_<%Y>/<date>",
]
manufacturer = "bruker"
include = [
    "300er",
]
display_name = "routine NMR (300 && 400 MHz)"
date_entry = "dd MMM yyyy"
allow_solvent = true
single_check_only = false


[spectrometers.hf]
spec_dir = "500-600er"
date = "%Y"
check_paths = [
    "<spec_dir>/<group name>/<date>",
]
manufacturer = "agilent"
display_name = "high-field spectrometers (500 && 600 MHz)"
date_entry = "yyyy"
allow_solvent = false
single_check_only = true
