# This file configures mora_the_explorer's *default* internal settings and should not be
# changed by anyone other than the NMR department.

# If you are looking for your user configuration, it is stored in the user's config.toml file, at:
# Windows:  %USERPROFILE%\AppData\Roaming\mora_the_explorer\config.toml
# macOS:    ~/Library/Application Support/mora_the_explorer/config.toml
# Linux:    $XDG_CONFIG_HOME/mora_the_explorer or ~/.config/mora_the_explorer/config.toml

# Values specified in the user config.toml take precedence over those specified here.

# Before bundling the app with pyinstaller or compiling it with pyside6-deploy,
# the config file must be transpiled to a QResource, which is done by running:
# `uv run pyside6-rcc ./src/mora_the_explorer/resources.qrc -o ./src/mora_the_explorer/resources.py`

version = 1

[options]
user = "mjm"
group = "gil"
spec = "neo400"
repeat_switch = false
repeat_delay = 5

[options.naming]
sample_format = "{user}-{user2}-{sample_id}"
measurement_format.bruker = "{user}-{user2}-{sample_id}_{instrument}_{submission_time:%d%m%y}_{temperature}k_{experiment}_{measurement_no}"
measurement_format.agilent = "{user}-{user2}-{sample_id}_{instrument}_{completion_time:%d%m%y}_{temperature}k_{experiment}_{measurement_no}"


[appearance]
start_button_colour = "#b88cce"


[paths]
# Paths to the server, different by OS
# Mount point probably needs to be changed by the user on macOS and Linux
windows = "//samba.public.os.wwu.de/usershare/projects/q_nmr-oc/nmr"
darwin = "/Volumes/usershare/projects/q_nmr-oc/nmr"  # darwin = macOS
linux = "~/usershare/projects/q_nmr-oc/nmr"
update = "mora_the_explorer"  # Where to check for app updates, relative to the server
save = ""  # The location spectra should be copied to - if empty, the user is asked on launch


[admin]
pattern_separator = '[\s_-]' # Note the single quotes! (= literal string)
version = "2.0.0b6"
email = "milner@uni-muenster.de"
changelog = """
- Update for move to new server
- Big rewrite, codebase is now much more structured and maintainable
- The search can be set to always check the current date which changes accordingly
- Spectra always sorted into subfolders by sample (like Agilent spectra)
- Paths are selected using the system file explorer
- Ability to specify the server address from the GUI (useful on macOS and Linux)
- Solvent, instrument, experiment, temperature metadata extracted on all spectrometers
- Metadata are saved to the measurement folder in mora.toml
- CLI and Python API work entirely independently of a GUI
"""


[groups]
# Available groups, listed in the style `group = group_name`
# `group` is the standard initialism used for each group's experiments and data
# institute-wide and is used in the search for Bruker spectra (as it must be included in
# the measurement title)
# `group` is the full name, used for folders of the group e.g. for the 500-600er
fer = "fernandez"
gar = "garcia"
gil = "gilmour"
glo = "glorius"
hei = "hein"
nae = "naesborg"
rav = "ravoo"
stu = "studer"

[groups.other]
# Groups that should be put in a separate overflow list called "Other" in the app
ac = "ac"
biochemie = "biochemie"
extern = "extern"
ipc = "ipc"
kb = "kb"
meet = "meet"
nuk = "nuk"
ocf = "ocf"
pharmazie = "pharmazie"


[spectrometers]
# Provide the following information for each spectrometer category:
#   manufacturer: the manufacturer of the spectrometer(s)
#   display_name: the text shown next to the button in the user interface
#       (note that some characters need escaping, e.g. write && for &)
#   measurement_pattern: the expected fields in the measurement title
#   date_entry: whether the user selects the full date "dd MMM yyyy" or just year "yyyy"
#   check_paths: the paths that should be searched for new spectra
#   archives: if spectra from previous years can't be found under check_paths, the
#       archive folders are checked in addition
#   include: other spectrometers which should be searched at the same time
#   restrict_to: the list of groups that should be able to see the spectrometer - if
#       this key is not used, the spectrometer will be visible to all
#   admin_only: whether the spectrometer should only be chooseable in admin mode
#   allow_solvent: whether to enable the folder naming option to include the solvent
#   single_check_only: whether users may use multiday and repeat checks for this spec
#
# Variables can be interpolated into the entries in `check_paths` and `archives`
# by wrapping them in curly brackets. The following variables can be used:
# - group         (the chosen group's ID)
# - group_name    (the chosen group's name)
# - date
#
# For `date`, it may be desirable to format it using e.g. `{date:%Y}` to get `2026`
# For the format codes see https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior

# Note that in TOML, single quotes can be used for a literal string to avoid
# having to use backslash escapes, which is very useful for regex patterns

[spectrometers.archiv]
manufacturer = "bruker"
display_name = "Pre-2020 archive (Bruker)"
measurement_pattern = '<group!>\_*<user_name>?\_*<user!>\_*<user2!>?\_*<sample_id!>' # Note the single quotes! (= literal string)
date_entry = "dd MMM yyyy"
check_paths = [
    "archiv/dpx300/{date:%y}-dpx300_{date:%Y}/{date:%b%d-%Y}",
    "archiv/av300/{date:%y}-av300_{date:%Y}/{date:%b%d-%Y}",
    "archiv/av400/{date:%y}-av400_{date:%Y}/{date:%b%d-%Y}",
    "archiv/neo400a/{date:%y}-neo400a_{date:%Y}/neo400a_{date:%b%d-%Y}",
    "archiv/neo400b/{date:%y}-neo400b_{date:%Y}/neo400b_{date:%b%d-%Y}",
    "archiv/neo400c/{date:%y}-neo400c_{date:%Y}/neo400c_{date:%b%d-%Y}",
]
admin_only = true
single_check_only = false

[spectrometers.av300]
manufacturer = "bruker"
display_name = "Studer group NMR only (300 MHz)"
measurement_pattern = '<group!>\_*<user_name>?\_*<user!>\_*<user2!>?\_*<sample_id!>'
date_entry = "dd MMM yyyy"
check_paths = [
    "av300/av1/{date:%b%d-%Y}",
]
archives = [
    "av300/av1/{date:%y}-av300_{date:%Y}/{date:%b%d-%Y}",
]
restrict_to = [
    "stu",
    "nae",
]
single_check_only = false

[spectrometers.neo400]
manufacturer = "bruker"
display_name = "Routine NMR (300 && 400 MHz)"
measurement_pattern = '<group!>\_*<user_name>?\_*<user!>\_*<user2!>?\_*<sample_id!>'
date_entry = "dd MMM yyyy"
check_paths = [
    "neo400/av1/neo400a_{date:%b%d-%Y}",
    "neo400/av1/neo400b_{date:%b%d-%Y}",
    "neo400/av1/neo400c_{date:%b%d-%Y}",
]
archives = [
    "neo400/av1/{date:%y}-neo400a_{date:%Y}/{date:%b%d-%Y}",
    "neo400/av1/{date:%y}-neo400b_{date:%Y}/{date:%b%d-%Y}",
    "neo400/av1/{date:%y}-neo400c_{date:%Y}/{date:%b%d-%Y}",
]
include = [ "av300" ]
single_check_only = false

[spectrometers.hf]
manufacturer = "agilent"
display_name = "High-field spectrometers (500 && 600 MHz)"
sample_pattern = '<user!><user2!>?<sample_id!>'
measurement_pattern = '<user!><user2!>?<sample_id!>_(\d{6})_<temperature>k_<experiment>_<measurement_no>\.fid'
date_entry = "yyyy"
check_paths = [
    "500-600er/{group_name}/{date:%Y}",
]
archives = [
    "archiv/500-600er/{group_name}/{date:%Y}",
]
single_check_only = true
