name: Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mora-the-explorer-linux.bin
          #- os: windows-latest
          #  artifact_name: mora-the-explorer-win.exe
          #- os: macos-latest
          #  artifact_name: mora-the-explorer-macos.app

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
    
      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"

      - name: Install Linux system deps
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          # Qt dependencies
          sudo apt install -y \
            libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxrender-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libatspi2.0-dev \
            '^libxcb.*-dev'
          # Nuitka dependencies
          sudo apt install -y ccache clang patchelf

      - name: Install the project
        run: uv sync --locked --dev

      - name: Run tests
        run: uv run pytest

      - name: Build binary (Linux)
        if: runner.os == 'Linux'
        run: |
          mkdir build
          uv run pyside6-deploy -c linux.spec
      
      - name: Debug build output
        if: always() && runner.os == 'Linux'
        run: find . -name "*.bin" -o -name "mora_the_explorer*" 2>/dev/null

      - name: Build binary (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          uv run pyside6-deploy -c win.spec

      - name: Build binary (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir build
          uv run pyside6-deploy -c mac.spec

      - name: Rename binary (Linux)
        if: runner.os == 'Linux'
        run: mv build/mora_the_explorer.bin ${{ matrix.artifact_name }}

      - name: Rename binary (Windows)
        if: runner.os == 'Windows'
        run: mv build/mora_the_explorer.exe ${{ matrix.artifact_name }}

      - name: Rename binary (macOS)
        if: runner.os == 'macOS'
        run: mv build/mora_the_explorer.app ${{ matrix.artifact_name }}

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

  release:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: dist/

      - uses: softprops/action-gh-release@v3
        with:
          files: dist/*
