name: CI

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"

      - name: Install the project
        run: uv sync --locked --dev

      - name: Lint
        run: uv run ruff check

      - name: Formatting check
        run: uv run ruff format --diff

      - name: Static analysis
        run: uv run ty check

  test:
    needs: check

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"

      - name: Install the project
        run: uv sync --locked --dev

      - name: Install Linux system deps
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          # Qt dependencies
          sudo apt install -y libegl1

      - name: Run tests
        run: uv run pytest -vv

  build:
    needs: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mora-the-explorer-linux
          - os: windows-latest
            artifact_name: mora-the-explorer-windows
          - os: macos-latest
            artifact_name: mora-the-explorer-macos

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.7"

      - name: Install the project
        run: uv sync --locked --dev

      - name: Install Linux system deps
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          # Qt dependencies
          sudo apt install -y \
            libfontconfig1-dev \
            libfreetype6-dev \
            libx11-dev \
            libx11-xcb-dev \
            libxext-dev \
            libxfixes-dev \
            libxi-dev \
            libxrender-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libatspi2.0-dev \
            '^libxcb.*-dev'
          # Nuitka dependencies
          sudo apt install -y ccache clang patchelf

      - name: Build pyinstaller bundle
        run: |
          uv run pyinstaller install/pyinstaller.spec

      - name: Build binary (Linux)
        if: runner.os == 'Linux'
        run: |
          rm -r build
          mkdir build
          uv run pyside6-deploy -c install/linux.spec

      - name: Rename bundle
        if: runner.os != 'Linux'
        run: mv dist/mora_the_explorer ${{ matrix.artifact_name }}

      - name: Rename binary (Linux)
        if: runner.os == 'Linux'
        run: mv build/mora_the_explorer.bin ${{ matrix.artifact_name }}

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}

      #- name: Upload release assets
      #  if: github.event_name != 'pull_request'
      #  env:
      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: gh release upload ${{ github.ref_name }} ${{ matrix.artifact_name }}
